### ISSUE TITLE
SSR options

### ISSUE THREAD

**Issue by mazipan** [adibfirman/react-lazy-viewport#3]
Need to skip calling window and documents on the SSR.
Let the client hydrated by itself.

**Comment by adibfirman** [comment]
Halo mas @mazipan 
thanks for the issue, i will try to fix on the SSR in the near of future :v:

**Comment by adibfirman** [comment]
Solved reference by this commit https://github.com/adibfirman/react-lazy-viewport/commit/f4ab750ab51f5387b5b5578bcc4c999c4d947a26
